-- M05 柯砺山战后 · 中文定稿（方向 3）
-- 权威：docs/story/chapters/chapter-01-钟下无名/dialogue/M02-现场与M05-战后.md 第二节

return {
    ['dlg.main_05.aft.ke1'] = '……抄本。半卷。在左边第三箱——没烧完。',
    ['dlg.main_05.aft.ke2'] = '够你们去撞钟。别谢我。谢了，像我求你们。',
    ['dlg.main_05.aft.huo_q'] = '你疯了还是活腻了？',
    ['dlg.main_05.aft.ke3'] = '活腻？我恨的是……他们写「天灾」两个字的时候，手都不抖。',
    ['dlg.main_05.aft.ke4'] = '你带外人上寨，我本该砍你。现在——你自己看他们像不像下一批官。',
    ['dlg.main_05.aft.huo_r'] = '我不跪官，也不跪你的火。',
    ['dlg.main_05.aft.liang1'] = '半卷在。残页有「沉钟」「子夜」字样。',
    ['dlg.main_05.aft.liang2'] = '伤者怎么处置？说一句，我照办。拖久了，两边的人都会来抢人。',
    ['dlg.main_05.aft.choice_prompt'] = '伤者怎么处置？',
    ['choice.main_05.official'] = '交给镇雾司。按案子走。',
    ['choice.main_05.relay'] = '交百驿会。先救人，再问话。',
    ['choice.main_05.huo'] = '交给你的人。',
    ['dlg.main_05.aft.off1'] = '……成。至少还有卷可查。',
    ['dlg.main_05.aft.off2'] = '官面的「按案子」，我见过。你选了，我记下。',
    ['dlg.main_05.aft.off3'] = '……好。让他们写我是匪。写惯了。',
    ['dlg.main_05.aft.off4'] = '先止住血再移交。死在路上，谁都没卷可查。',
    ['dlg.main_05.aft.rel1'] = '稳。会里的人懂分寸——大多时候。',
    ['dlg.main_05.aft.rel2'] = '总比直接送官强。',
    ['dlg.main_05.aft.rel3'] = '……会里的车，也跑官的货。别天真。',
    ['dlg.main_05.aft.rel4'] = '看管地点与经手人，我要记名。日后对质用。',
    ['dlg.main_05.aft.huo1'] = '……谢。不是谢你纵容，是谢你没把寨民一锅端。',
    ['dlg.main_05.aft.huo2'] = '人在寨里，官面要人时，你扛得住？',
    ['dlg.main_05.aft.huo3'] = '扛不住就跑。跑之前，先让他活着。',
    ['dlg.main_05.aft.huo4'] = '小满。别学我。也别学他们。',
    ['dlg.main_05.aft.huo5'] = '闭嘴养伤。',
    ['dlg.main_05.aft.close1'] = '半卷指向沉钟院。子夜潮起，水路才显。',
    ['dlg.main_05.aft.close2'] = '钟油从哪来，院里也许有旧账。',
    ['dlg.main_05.aft.close3'] = '院里有人守。守了很久。别当空屋子。',
    ['dlg.main_05.aft.close4'] = '整队。能走的走。',
    ['dlg.main_05.aft.ke_last'] = '撞了钟……记得谁下的令。别只记得谁挨了刀。',
    ['dlg.main_05.aft.end'] = '',
}
