-- System 15 owns these failures. Foundation error codes remain unchanged.

return {
    FACTION_ARGUMENT_INVALID = 'FACTION_ARGUMENT_INVALID',
    FACTION_ALREADY_JOINED = 'FACTION_ALREADY_JOINED',
    FACTION_NOT_CANDIDATE = 'FACTION_NOT_CANDIDATE',
    FACTION_NOT_MEMBER = 'FACTION_NOT_MEMBER',
    FACTION_NOT_FOUND = 'FACTION_NOT_FOUND',
    FACTION_PROMOTION_NOT_READY = 'FACTION_PROMOTION_NOT_READY',
    FACTION_VALUE_OVERFLOW = 'FACTION_VALUE_OVERFLOW',
    FACTION_RECEIPT_CONFLICT = 'FACTION_RECEIPT_CONFLICT',
    FACTION_COMMAND_CONFLICT = 'FACTION_COMMAND_CONFLICT',
    FACTION_STATUS_INVALID = 'FACTION_STATUS_INVALID',
}
