-- Create-character candidate roster (presentation catalog).
-- Domain authority remains character_id / display_name on the slot; models are showroom-only.

return {
    {
        id = 'hero_mist',
        glyph = '雾',
        catalog_name = '雾中客',
        role = '无名剑客',
        tag = '均衡 · 剑',
        intro = '钟下无碑。步履轻，刃意沉。只问雾开时能否见路。',
        stats = { strength = 12, constitution = 12, agility = 12, inner_power = 12 },
        chapter_hint = '卷一 · 开局',
        -- Official / project editor_model ids (cloudresdependence).
        model_id = 10015,
        accent = { 210, 190, 140 },
    },
    {
        id = 'hero_blade',
        glyph = '刃',
        catalog_name = '霜刃行',
        role = '快刀客',
        tag = '爆发 · 刀',
        intro = '刀出如霜，收势不回头。认准一处，连进三招。',
        stats = { strength = 15, constitution = 10, agility = 14, inner_power = 9 },
        chapter_hint = '卷一 · 开局',
        model_id = 10022,
        accent = { 180, 200, 210 },
    },
    {
        id = 'hero_herb',
        glyph = '药',
        catalog_name = '青囊影',
        role = '行医隐侠',
        tag = '稳健 · 杂学',
        intro = '青囊系肘。言少算深，先保命，再论胜负。',
        stats = { strength = 9, constitution = 15, agility = 10, inner_power = 14 },
        chapter_hint = '卷一 · 开局',
        model_id = 100006,
        accent = { 120, 170, 130 },
    },
    {
        id = 'hero_wind',
        glyph = '风',
        catalog_name = '踏云生',
        role = '轻功客',
        tag = '机变 · 轻功',
        intro = '檐角一点，雾面三折。不恋缠斗，专找夹缝活路。',
        stats = { strength = 10, constitution = 10, agility = 16, inner_power = 12 },
        chapter_hint = '卷一 · 开局',
        model_id = 100028,
        accent = { 150, 185, 190 },
    },
    {
        id = 'hero_bow',
        glyph = '弦',
        catalog_name = '暮弦',
        role = '冷弓手',
        tag = '远程 · 弓',
        intro = '十步外才是她的道理。话少，箭更少。',
        stats = { strength = 11, constitution = 10, agility = 14, inner_power = 13 },
        chapter_hint = '卷一 · 开局',
        model_id = 103014,
        accent = { 170, 145, 120 },
    },
    {
        id = 'hero_monk',
        glyph = '禅',
        catalog_name = '半偈',
        role = '还俗僧',
        tag = '防御 · 拳',
        intro = '袈裟已卸，戒疤还在。今日只问能否走过这截径。',
        stats = { strength = 13, constitution = 16, agility = 8, inner_power = 11 },
        chapter_hint = '卷一 · 开局',
        model_id = 206278,
        accent = { 200, 175, 120 },
    },
}
