-- System 08 owns these failures.

return {
    EQUIPMENT_ARGUMENT_INVALID = 'EQUIPMENT_ARGUMENT_INVALID',
    EQUIPMENT_UNKNOWN = 'EQUIPMENT_UNKNOWN',
    EQUIPMENT_CONFIG_BROKEN = 'EQUIPMENT_CONFIG_BROKEN',
    EQUIPMENT_DEPRECATED = 'EQUIPMENT_DEPRECATED',
    EQUIPMENT_NOT_FOUND = 'EQUIPMENT_NOT_FOUND',
    EQUIPMENT_DRAFT_INVALID = 'EQUIPMENT_DRAFT_INVALID',
    EQUIPMENT_INCOMPATIBLE = 'EQUIPMENT_INCOMPATIBLE',
    EQUIPMENT_SLOT_OCCUPIED = 'EQUIPMENT_SLOT_OCCUPIED',
    EQUIPMENT_SLOT_EMPTY = 'EQUIPMENT_SLOT_EMPTY',
    EQUIPMENT_OWNED_BY_OTHER_CHARACTER = 'EQUIPMENT_OWNED_BY_OTHER_CHARACTER',
    EQUIPMENT_ALREADY_EQUIPPED = 'EQUIPMENT_ALREADY_EQUIPPED',
    EQUIPMENT_CHARACTER_LEVEL_TOO_LOW = 'EQUIPMENT_CHARACTER_LEVEL_TOO_LOW',
    EQUIPMENT_WEAPON_ROUTE_MISMATCH = 'EQUIPMENT_WEAPON_ROUTE_MISMATCH',
    EQUIPMENT_TAG_REQUIRED = 'EQUIPMENT_TAG_REQUIRED',
    EQUIPMENT_ENHANCE_MAX_LEVEL = 'EQUIPMENT_ENHANCE_MAX_LEVEL',
    EQUIPMENT_STAT_OVERFLOW = 'EQUIPMENT_STAT_OVERFLOW',
    EQUIPMENT_AFFIX_POOL_EMPTY = 'EQUIPMENT_AFFIX_POOL_EMPTY',
    EQUIPMENT_CONTRIBUTION_INVALID = 'EQUIPMENT_CONTRIBUTION_INVALID',
    EQUIPMENT_INSTANCE_INVALID = 'EQUIPMENT_INSTANCE_INVALID',
}
