-- Stable foundation error codes. System-specific modules own their own codes.

return {
    INVALID_ARGUMENT = 'INVALID_ARGUMENT',
    ID_INVALID = 'ID_INVALID',
    ID_TOO_LONG = 'ID_TOO_LONG',
    IDEMPOTENCY_KEY_REUSED = 'IDEMPOTENCY_KEY_REUSED',
    CANONICAL_VALUE_INVALID = 'CANONICAL_VALUE_INVALID',
    CANONICAL_SCHEMA_INVALID = 'CANONICAL_SCHEMA_INVALID',
    SCHEMA_VALIDATION_FAILED = 'SCHEMA_VALIDATION_FAILED',
    REGISTRY_DUPLICATE = 'REGISTRY_DUPLICATE',
    REGISTRY_SEALED = 'REGISTRY_SEALED',
    REGISTRY_ENTRY_NOT_FOUND = 'REGISTRY_ENTRY_NOT_FOUND',
    SECTION_OWNER_CONFLICT = 'SECTION_OWNER_CONFLICT',
    SECTION_WRITE_FORBIDDEN = 'SECTION_WRITE_FORBIDDEN',
    PORT_CONTRACT_INVALID = 'PORT_CONTRACT_INVALID',
    PLATFORM_UNAVAILABLE = 'PLATFORM_UNAVAILABLE',
    PLATFORM_RESULT_UNKNOWN = 'PLATFORM_RESULT_UNKNOWN',
    SAVE_ENVELOPE_INVALID = 'SAVE_ENVELOPE_INVALID',
    DOMAIN_EVENT_INVALID = 'DOMAIN_EVENT_INVALID',
    COMBAT_EVENT_INVALID = 'COMBAT_EVENT_INVALID',
    CONTRACT_VALIDATION_FAILED = 'CONTRACT_VALIDATION_FAILED',
    TABLE_SHAPE_INVALID = 'TABLE_SHAPE_INVALID',
}
