-- System 09 owns these failures.

return {
    INVENTORY_ARGUMENT_INVALID = 'INVENTORY_ARGUMENT_INVALID',
    INVENTORY_ITEM_UNKNOWN = 'INVENTORY_ITEM_UNKNOWN',
    INVENTORY_FULL = 'INVENTORY_FULL',
    INVENTORY_ITEM_CAP_REACHED = 'INVENTORY_ITEM_CAP_REACHED',
    INVENTORY_ITEM_INSUFFICIENT = 'INVENTORY_ITEM_INSUFFICIENT',
    INVENTORY_ENTRY_UNSUPPORTED = 'INVENTORY_ENTRY_UNSUPPORTED',
    INVENTORY_SAVE_INVALID = 'INVENTORY_SAVE_INVALID',
    INVENTORY_SAVE_LIMIT_EXCEEDED = 'INVENTORY_SAVE_LIMIT_EXCEEDED',
    INVENTORY_REVISION_CONFLICT = 'INVENTORY_REVISION_CONFLICT',
}
