-- System 10 owns these failures. Foundation error codes remain unchanged.

return {
    REWARD_ARGUMENT_INVALID = 'REWARD_ARGUMENT_INVALID',
    REWARD_BUNDLE_INVALID = 'REWARD_BUNDLE_INVALID',
    REWARD_CATALOG_INVALID = 'REWARD_CATALOG_INVALID',
    REWARD_REFERENCE_NOT_FOUND = 'REWARD_REFERENCE_NOT_FOUND',
    REWARD_NESTING_INVALID = 'REWARD_NESTING_INVALID',
    REWARD_LEVEL_XP_FORBIDDEN = 'REWARD_LEVEL_XP_FORBIDDEN',
    REWARD_EXPAND_FAILED = 'REWARD_EXPAND_FAILED',
}
