-- System 01 owns these failures. Foundation error codes remain unchanged.

return {
    CHARACTER_ARGUMENT_INVALID = 'CHARACTER_ARGUMENT_INVALID',
    CHARACTER_PRIMARY_ATTRIBUTES_INVALID = 'CHARACTER_PRIMARY_ATTRIBUTES_INVALID',
    CHARACTER_LEVEL_CURVE_INVALID = 'CHARACTER_LEVEL_CURVE_INVALID',
    CHARACTER_XP_OUT_OF_RANGE = 'CHARACTER_XP_OUT_OF_RANGE',
    CHARACTER_FORMULA_INVALID = 'CHARACTER_FORMULA_INVALID',
    CHARACTER_CONTRIBUTION_INVALID = 'CHARACTER_CONTRIBUTION_INVALID',
    CHARACTER_BUILD_INVALID = 'CHARACTER_BUILD_INVALID',
}
