-- System 06 owns these failures.

return {
    COMBAT_ARGUMENT_INVALID = 'COMBAT_ARGUMENT_INVALID',
    COMBAT_SNAPSHOT_INVALID = 'COMBAT_SNAPSHOT_INVALID',
    COMBAT_STATE_INVALID = 'COMBAT_STATE_INVALID',
    COMBAT_PHASE_INVALID = 'COMBAT_PHASE_INVALID',
    COMBAT_REVISION_CONFLICT = 'COMBAT_REVISION_CONFLICT',
    COMBAT_COMMAND_TYPE_UNSUPPORTED = 'COMBAT_COMMAND_TYPE_UNSUPPORTED',
    COMBAT_ITEM_USE_UNSUPPORTED = 'COMBAT_ITEM_USE_UNSUPPORTED',
    COMBAT_COMMAND_IDEMPOTENT_REPLAY = 'COMBAT_COMMAND_IDEMPOTENT_REPLAY',
    COMBAT_ACTOR_INVALID = 'COMBAT_ACTOR_INVALID',
    COMBAT_MOVE_INVALID = 'COMBAT_MOVE_INVALID',
    COMBAT_TARGET_INVALID = 'COMBAT_TARGET_INVALID',
    COMBAT_ALREADY_FINISHED = 'COMBAT_ALREADY_FINISHED',
    COMBAT_NOT_AUTO = 'COMBAT_NOT_AUTO',
    COMBAT_RULES_MISMATCH = 'COMBAT_RULES_MISMATCH',
}
