-- System 13 owns these failures.

return {
    DIALOGUE_ARGUMENT_INVALID = 'DIALOGUE_ARGUMENT_INVALID',
    DIALOGUE_CONFIG_MISSING = 'DIALOGUE_CONFIG_MISSING',
    DIALOGUE_CONFIG_BROKEN = 'DIALOGUE_CONFIG_BROKEN',
    DIALOGUE_UNKNOWN = 'DIALOGUE_UNKNOWN',
    DIALOGUE_NODE_UNKNOWN = 'DIALOGUE_NODE_UNKNOWN',
    DIALOGUE_CHOICE_UNKNOWN = 'DIALOGUE_CHOICE_UNKNOWN',
    DIALOGUE_DEPRECATED = 'DIALOGUE_DEPRECATED',
    DIALOGUE_BUSY = 'DIALOGUE_BUSY',
    DIALOGUE_NOT_ACTIVE = 'DIALOGUE_NOT_ACTIVE',
    DIALOGUE_STATE_MISMATCH = 'DIALOGUE_STATE_MISMATCH',
    DIALOGUE_PHASE_INVALID = 'DIALOGUE_PHASE_INVALID',
    DIALOGUE_CHOICE_STALE = 'DIALOGUE_CHOICE_STALE',
    DIALOGUE_LOOP_GUARD = 'DIALOGUE_LOOP_GUARD',
    DIALOGUE_INTERRUPT_DENIED = 'DIALOGUE_INTERRUPT_DENIED',
    DIALOGUE_RECEIPT_CONFLICT = 'DIALOGUE_RECEIPT_CONFLICT',
    DIALOGUE_ALREADY_ENDED = 'DIALOGUE_ALREADY_ENDED',
    DIALOGUE_BUILD_INVALID = 'DIALOGUE_BUILD_INVALID',
    DIALOGUE_SAVE_INVALID = 'DIALOGUE_SAVE_INVALID',
    DIALOGUE_SAVE_LIMIT_EXCEEDED = 'DIALOGUE_SAVE_LIMIT_EXCEEDED',
    DIALOGUE_SAVE_VERSION_UNSUPPORTED = 'DIALOGUE_SAVE_VERSION_UNSUPPORTED',
}
