-- System 18 owns these failures. Foundation error codes remain unchanged.

return {
    SAVE_ARGUMENT_INVALID = 'SAVE_ARGUMENT_INVALID',
    SAVE_DOWNLOAD_FAILED = 'SAVE_DOWNLOAD_FAILED',
    SAVE_CORRUPT = 'SAVE_CORRUPT',
    SAVE_NOT_FOUND = 'SAVE_NOT_FOUND',
    SAVE_EXISTENCE_UNKNOWN = 'SAVE_EXISTENCE_UNKNOWN',
    SAVE_OWNER_MISMATCH = 'SAVE_OWNER_MISMATCH',
    SAVE_REVISION_CONFLICT = 'SAVE_REVISION_CONFLICT',
    SAVE_RESULT_UNKNOWN = 'SAVE_RESULT_UNKNOWN',
    ORPHAN_SLOT_WRITE = 'ORPHAN_SLOT_WRITE',
    SAVE_SESSION_INVALID = 'SAVE_SESSION_INVALID',
    SAVE_CHECKPOINT_INVALID = 'SAVE_CHECKPOINT_INVALID',
}
