-- System 02 companion / affection domain failure codes.

return {
    COMPANION_ARGUMENT_INVALID = 'COMPANION_ARGUMENT_INVALID',
    COMPANION_ENTRY_INVALID = 'COMPANION_ENTRY_INVALID',
    COMPANION_DISCOVERY_STATE_INVALID = 'COMPANION_DISCOVERY_STATE_INVALID',
    COMPANION_DISCOVERY_REGRESSION = 'COMPANION_DISCOVERY_REGRESSION',
    COMPANION_NOT_RECRUITED = 'COMPANION_NOT_RECRUITED',
    COMPANION_AVAILABILITY_INVALID = 'COMPANION_AVAILABILITY_INVALID',
    COMPANION_RECRUITMENT_EVIDENCE_INVALID = 'COMPANION_RECRUITMENT_EVIDENCE_INVALID',
    COMPANION_AFFECTION_INVALID = 'COMPANION_AFFECTION_INVALID',
    COMPANION_AFFECTION_MAX = 'COMPANION_AFFECTION_MAX',
}
