-- System 05 owns these failures.

return {
    EFFECT_ARGUMENT_INVALID = 'EFFECT_ARGUMENT_INVALID',
    EFFECT_CONFIG_MISSING = 'EFFECT_CONFIG_MISSING',
    EFFECT_TARGET_INVALID = 'EFFECT_TARGET_INVALID',
    EFFECT_BUDGET_EXCEEDED = 'EFFECT_BUDGET_EXCEEDED',
    EFFECT_CALLER_UNAUTHORIZED = 'EFFECT_CALLER_UNAUTHORIZED',
    EFFECT_STATUS_LIMIT = 'EFFECT_STATUS_LIMIT',
    EFFECT_STATUS_IMMUNE = 'EFFECT_STATUS_IMMUNE',
    EFFECT_OPERATION_UNSUPPORTED = 'EFFECT_OPERATION_UNSUPPORTED',
    EFFECT_RUNTIME_INVALID = 'EFFECT_RUNTIME_INVALID',
    EFFECT_CONDITION_INVALID = 'EFFECT_CONDITION_INVALID',
    EFFECT_REVISION_CONFLICT = 'EFFECT_REVISION_CONFLICT',
    EFFECT_GRAPH_INVALID = 'EFFECT_GRAPH_INVALID',
    EFFECT_TOOLTIP_UNRESOLVED = 'EFFECT_TOOLTIP_UNRESOLVED',
}
