return {
    PARTY_ARGUMENT_INVALID = 'PARTY_ARGUMENT_INVALID',
    PARTY_DUPLICATE_MEMBER = 'PARTY_DUPLICATE_MEMBER',
    PARTY_POSITION_OCCUPIED = 'PARTY_POSITION_OCCUPIED',
    PARTY_MEMBER_UNKNOWN = 'PARTY_MEMBER_UNKNOWN',
    PARTY_LEADER_INVALID = 'PARTY_LEADER_INVALID',
    PARTY_SIZE_INVALID = 'PARTY_SIZE_INVALID',
    PARTY_REVISION_CONFLICT = 'PARTY_REVISION_CONFLICT',
    PARTY_CONTEXT_INVALID = 'PARTY_CONTEXT_INVALID',
    PARTY_NOT_READY = 'PARTY_NOT_READY',
}
